version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:1111
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    command: ["tinychat"]
